name: Nightly Build and Push to Docker Hub

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  
  test:
    name: Run Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  

      - name: Run Tests
        
        
        run: |
          pytest 

      - name: Send email if test fail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Nightly Build - Test Failed"
          to: ${{ secrets.MAIL_FROM }}
          from: "${{ secrets.MAIL_FROM_NAME }} <${{ secrets.MAIL_FROM }}>"
          body: |
            "The nightly build tests have failed. The build process will execute"

  build-and-push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    environment: DATABASE_URL
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Web Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud-web:nightly-build -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud-web:nightly-build

      - name: Push Celery Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud-celery:nightly-build -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-beyond-crud-celery:nightly-build

      - name: Send failure email if image push fails
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Nightly Build - Docker Hub Image Push Failed!"
          to: ${{ secrets.MAIL_FROM }}
          from: "${{ secrets.MAIL_FROM_NAME }} <${{ secrets.MAIL_FROM }}>"
          body: |
            "The nightly build failed to push Docker images to Docker Hub."